# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Leverify.DESKTOP-LSB4JMG\Downloads\GUIs\SE3 - Copy.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import ctypes
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QTableWidgetItem
# QApplication, QPushButton, QVBoxLayout, QWidget,QTableWidget,QTableWidgetItem
# from PyQt5.QtCore import QObject, QThread, pyqtSignal,pyqtSlot
import sys
import time
import datetime
from MainFile import MainFile
from GoogleSheet_stock import GoogleSheet_SE
import csv

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        myappid = 'leverify.automation.stockestimation.1'  # arbitrary string
        ctypes.windll.shell32.SetCurrentProcessExplicitAppUserModelID(myappid)
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1641, 1107)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./resources/icon1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # icon.addPixmap(QtGui.QPixmap("C:\\Users\\Leverify\\Documents\\stock estimation code\\offers_stock_15K+\\resources\\icon1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setStyleSheet("background-color: #1f2a7a;")
        MainWindow.setIconSize(QtCore.QSize(36, 36))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem = QtWidgets.QSpacerItem(0, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_6.addItem(spacerItem, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("color:#1f2a7a;")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_usingFile = QtWidgets.QWidget()
        self.tab_usingFile.setObjectName("tab_usingFile")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_usingFile)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_usingFile)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(11)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setStyleSheet("background-color:transparent;\n"
"color:white;\n"
"font:bold 15px;\n"
"border-radius:10px;\n"
"border-color:white;\n"
"border-width:1px;\n"
"border-style:outset;\n"
"height:30")
        self.groupBox_6.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_3.setContentsMargins(-1, 30, -1, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_select_excel_file_asterik = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_select_excel_file_asterik.sizePolicy().hasHeightForWidth())
        self.label_select_excel_file_asterik.setSizePolicy(sizePolicy)
        self.label_select_excel_file_asterik.setStyleSheet("border:none;color:red;")
        self.label_select_excel_file_asterik.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_select_excel_file_asterik.setIndent(0)
        self.label_select_excel_file_asterik.setObjectName("label_select_excel_file_asterik")
        self.gridLayout_3.addWidget(self.label_select_excel_file_asterik, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("\n"
".QLabel#label_2 {border:none;}")
        self.label_2.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem1, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(30, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem2, 2, 2, 1, 1)
        self.lineEdit_file_name = QtWidgets.QLineEdit(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_file_name.sizePolicy().hasHeightForWidth())
        self.lineEdit_file_name.setSizePolicy(sizePolicy)
        self.lineEdit_file_name.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_file_name.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_file_name.setStyleSheet("background-color:transparent;\n"
"color:white;\n"
"font:15px;\n"
"border-radius:10px;\n"
"border-color:white;\n"
"border-width:1px;\n"
"border-style:outset;\n"
"height:30")
        self.lineEdit_file_name.setText("")
        self.lineEdit_file_name.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_file_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_file_name.setObjectName("lineEdit_file_name")
        self.gridLayout_3.addWidget(self.lineEdit_file_name, 1, 2, 1, 2)
        self.pushButton_choice_file = QtWidgets.QPushButton(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_choice_file.sizePolicy().hasHeightForWidth())
        self.pushButton_choice_file.setSizePolicy(sizePolicy)
        self.pushButton_choice_file.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_choice_file.setStyleSheet("background-color:transparent;\n"
"color:white;\n"
"font:bold 15px;\n"
"border-radius:10px;\n"
"border-color:white;\n"
"border-width:1px;\n"
"border-style:outset;\n"
"height:30")
        self.pushButton_choice_file.setObjectName("pushButton_choice_file")
        self.gridLayout_3.addWidget(self.pushButton_choice_file, 1, 4, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_6, 0, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_usingFile)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(15)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("background-color:transparent;\n"
"color:white;\n"
"border-radius:10px;\n"
"border-color:white;\n"
"border-width:1px;\n"
"border-style:outset;\n"
"height:30")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setContentsMargins(0, 13, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_save = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_save.sizePolicy().hasHeightForWidth())
        self.pushButton_save.setSizePolicy(sizePolicy)
        self.pushButton_save.setAutoFillBackground(False)
        self.pushButton_save.setStyleSheet("background-color: #1f2a7a;\n"
"color:white;\n"
"font:bold 10px;\n"
"border-radius:10px;\n"
"border-color:transparent;\n"
"border-width:2px;\n"
"border-style:outset;\n"
"padding:5px;\n"
"margin-right:10px;\n"
"QToolTip { color: white; background-color: #1f2a7a; border: 1px solid white;padding:-3px }\n"
"\n"
"")
        self.pushButton_save.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./resources/img3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # icon1.addPixmap(QtGui.QPixmap("C:\\Users\\Leverify\\Documents\\stock estimation code\\offers_stock_15K+\\resources\\img3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_save.setIcon(icon1)
        self.pushButton_save.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_save.setObjectName("pushButton_save")
        self.gridLayout_4.addWidget(self.pushButton_save, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(1000, 0, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 0, 0, 1, 1)
        self.tableWidget_employees = QtWidgets.QTableWidget(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_employees.sizePolicy().hasHeightForWidth())
        self.tableWidget_employees.setSizePolicy(sizePolicy)
        self.tableWidget_employees.setStyleSheet("border:1px solid white;\n"
"background-color: rgb(255, 255, 255);\n"
"color:black;")
        self.tableWidget_employees.setObjectName("tableWidget_employees")
        self.tableWidget_employees.setColumnCount(0)
        self.tableWidget_employees.setRowCount(0)
        self.gridLayout_4.addWidget(self.tableWidget_employees, 2, 0, 1, 3)
        self.pushButton_clear = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_clear.sizePolicy().hasHeightForWidth())
        self.pushButton_clear.setSizePolicy(sizePolicy)
        self.pushButton_clear.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_clear.setAutoFillBackground(False)
        self.pushButton_clear.setStyleSheet("background-color: #1f2a7a;\n"
"color:white;\n"
"font:bold 10px;\n"
"border-radius:10px;\n"
"border-color:transparent;\n"
"border-width:2px;\n"
"border-style:outset;\n"
"padding:5px;\n"
"margin-right:10px;\n"
"QToolTip { color: white; background-color: #1f2a7a; border: 1px solid white;padding:-3px }\n"
"\n"
"")
        self.pushButton_clear.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./resources/img1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # icon2.addPixmap(QtGui.QPixmap("C:\\Users\\Leverify\\Documents\\stock estimation code\\offers_stock_15K+\\resources\\img1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_clear.setIcon(icon2)
        self.pushButton_clear.setIconSize(QtCore.QSize(50, 45))
        self.pushButton_clear.setAutoRepeatInterval(100)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.gridLayout_4.addWidget(self.pushButton_clear, 0, 2, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_3, 1, 0, 1, 3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_usingFile)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet("background-color:transparent;\n"
"color:white;\n"
"border-radius:10px;\n"
"border-color:white;\n"
"border-width:1px;\n"
"border-style:outset;\n"
"height:30")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_7.setContentsMargins(-1, 30, -1, -1)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_overallExportStatus = QtWidgets.QLabel(self.groupBox_4)
        self.label_overallExportStatus.setStyleSheet("border:none;\n"
"color:white;\n"
"font:bold 24px;")
        self.label_overallExportStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.label_overallExportStatus.setObjectName("label_overallExportStatus")
        self.gridLayout_7.addWidget(self.label_overallExportStatus, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("border:noe")
        self.label_5.setObjectName("label_5")
        self.gridLayout_7.addWidget(self.label_5, 1, 1, 1, 1)
        self.progressBar_export = QtWidgets.QProgressBar(self.groupBox_4)
        self.progressBar_export.setStyleSheet("background-color:rgb(208, 28, 12);\n"
"color:white;\n"
"font:20px;\n"
"border-radius:10px;\n"
"border-color:white;\n"
"border-width:2px;\n"
"\n"
"")
        self.progressBar_export.setProperty("value", 0)
        self.progressBar_export.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_export.setObjectName("progressBar_export")
        self.gridLayout_7.addWidget(self.progressBar_export, 4, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.groupBox_4)
        self.line_2.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.line_2.setFont(font)
        self.line_2.setStyleSheet("border:1px solid white;")
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(0)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.gridLayout_7.addWidget(self.line_2, 6, 0, 1, 3)
        self.line = QtWidgets.QFrame(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMinimumSize(QtCore.QSize(0, 6))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_7.addWidget(self.line, 5, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setStyleSheet("border:none;")
        self.groupBox_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_3.setContentsMargins(-1, 30, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textBrowser_console = QtWidgets.QTextBrowser(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.textBrowser_console.setFont(font)
        self.textBrowser_console.setStyleSheet("background:black;\n"
"color:white")
        self.textBrowser_console.setObjectName("textBrowser_console")
        self.verticalLayout_3.addWidget(self.textBrowser_console)
        self.gridLayout_7.addWidget(self.groupBox_5, 7, 0, 1, 3)
        self.pushButton_export = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_export.sizePolicy().hasHeightForWidth())
        self.pushButton_export.setSizePolicy(sizePolicy)
        self.pushButton_export.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_export.setStyleSheet("background-color: white;\n"
"color:#1f2a7a;\n"
"font:bold 10px;\n"
"border-radius:10px;\n"
"border-color:transparent;\n"
"padding:5px;\n"
"margin-right:10px;\n"
"QToolTip { color: #1f2a7a; background-color: #1f2a7a; border: 1px solid white;padding:-3px }\n"
"\n"
"")
        self.pushButton_export.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("./resources/img4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # icon3.addPixmap(QtGui.QPixmap("C:\\Users\\Leverify\\Documents\\stock estimation code\\offers_stock_15K+\\resources\\img4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_export.setIcon(icon3)
        self.pushButton_export.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_export.setObjectName("pushButton_export")
        self.gridLayout_7.addWidget(self.pushButton_export, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_4, 1, 3, 1, 1)
        self.groupBox_initial_settings = QtWidgets.QGroupBox(self.tab_usingFile)
        self.groupBox_initial_settings.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBox_initial_settings.setFont(font)
        self.groupBox_initial_settings.setStyleSheet("background-color:transparent;\n"
"color:white;\n"
"font:bold 15px;\n"
"border-radius:10px;\n"
"border-color:white;\n"
"border-width:1px;\n"
"border-style:outset;\n"
"height:30")
        self.groupBox_initial_settings.setObjectName("groupBox_initial_settings")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_initial_settings)
        self.gridLayout.setObjectName("gridLayout")
        self.label_15 = QtWidgets.QLabel(self.groupBox_initial_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color:red;border:none")
        self.label_15.setScaledContents(False)
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 0, 1, 1, 2)
        self.radioButton_source_excel_sheet = QtWidgets.QRadioButton(self.groupBox_initial_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_source_excel_sheet.sizePolicy().hasHeightForWidth())
        self.radioButton_source_excel_sheet.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.radioButton_source_excel_sheet.setFont(font)
        self.radioButton_source_excel_sheet.setStyleSheet("border:none")
        self.radioButton_source_excel_sheet.setAutoRepeat(False)
        self.radioButton_source_excel_sheet.setObjectName("radioButton_source_excel_sheet")
        self.gridLayout.addWidget(self.radioButton_source_excel_sheet, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_initial_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("border:none")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.radioButton_source_google_sheet = QtWidgets.QRadioButton(self.groupBox_initial_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_source_google_sheet.sizePolicy().hasHeightForWidth())
        self.radioButton_source_google_sheet.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.radioButton_source_google_sheet.setFont(font)
        self.radioButton_source_google_sheet.setStyleSheet("border:none")
        self.radioButton_source_google_sheet.setObjectName("radioButton_source_google_sheet")
        self.gridLayout.addWidget(self.radioButton_source_google_sheet, 0, 5, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 4, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_initial_settings, 0, 0, 1, 1)
        self.groupBox_google_sheet_settings = QtWidgets.QGroupBox(self.tab_usingFile)
        self.groupBox_google_sheet_settings.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.groupBox_google_sheet_settings.sizePolicy().hasHeightForWidth())
        self.groupBox_google_sheet_settings.setSizePolicy(sizePolicy)
        self.groupBox_google_sheet_settings.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.groupBox_google_sheet_settings.setFont(font)
        self.groupBox_google_sheet_settings.setStyleSheet("background-color:transparent;\n"
"color:white;\n"
"font:bold 15px;\n"
"border-radius:10px;\n"
"border-color:white;\n"
"border-width:1px;\n"
"border-style:outset;\n"
"height:30")
        self.groupBox_google_sheet_settings.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.groupBox_google_sheet_settings.setObjectName("groupBox_google_sheet_settings")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_google_sheet_settings)
        self.gridLayout_5.setContentsMargins(-1, 30, -1, 13)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox_google_sheet_settings)
        self.label_4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border:none;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 1, 0, 1, 1)
        self.lineEdit_googlesheet_id = QtWidgets.QLineEdit(self.groupBox_google_sheet_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_googlesheet_id.sizePolicy().hasHeightForWidth())
        self.lineEdit_googlesheet_id.setSizePolicy(sizePolicy)
        self.lineEdit_googlesheet_id.setMinimumSize(QtCore.QSize(0, 31))
        self.lineEdit_googlesheet_id.setStyleSheet("background-color:transparent;\n"
"color:white;\n"
"font:15px;\n"
"border-radius:10px;\n"
"border-color:white;\n"
"border-width:1px;\n"
"border-style:outset;\n"
"height:30")
        self.lineEdit_googlesheet_id.setText("")
        self.lineEdit_googlesheet_id.setObjectName("lineEdit_googlesheet_id")
        self.gridLayout_5.addWidget(self.lineEdit_googlesheet_id, 1, 2, 1, 2)
        self.lineEdit_googlesheet_name = QtWidgets.QLineEdit(self.groupBox_google_sheet_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_googlesheet_name.sizePolicy().hasHeightForWidth())
        self.lineEdit_googlesheet_name.setSizePolicy(sizePolicy)
        self.lineEdit_googlesheet_name.setMinimumSize(QtCore.QSize(0, 31))
        self.lineEdit_googlesheet_name.setStyleSheet("background-color:transparent;\n"
"color:white;\n"
"font:15px;\n"
"border-radius:10px;\n"
"border-color:white;\n"
"border-width:1px;\n"
"border-style:outset;\n"
"height:30")
        self.lineEdit_googlesheet_name.setText("")
        self.lineEdit_googlesheet_name.setObjectName("lineEdit_googlesheet_name")
        self.gridLayout_5.addWidget(self.lineEdit_googlesheet_name, 1, 7, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem5, 1, 4, 1, 1)
        self.label_google_sheet_name_asterik = QtWidgets.QLabel(self.groupBox_google_sheet_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_google_sheet_name_asterik.sizePolicy().hasHeightForWidth())
        self.label_google_sheet_name_asterik.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_google_sheet_name_asterik.setFont(font)
        self.label_google_sheet_name_asterik.setStyleSheet("border:none;")
        self.label_google_sheet_name_asterik.setAlignment(QtCore.Qt.AlignCenter)
        self.label_google_sheet_name_asterik.setObjectName("label_google_sheet_name_asterik")
        self.gridLayout_5.addWidget(self.label_google_sheet_name_asterik, 1, 5, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_5.addItem(spacerItem6, 0, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_5.addItem(spacerItem7, 2, 2, 1, 1)
        self.label_google_sheet_id_asterik = QtWidgets.QLabel(self.groupBox_google_sheet_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_google_sheet_id_asterik.sizePolicy().hasHeightForWidth())
        self.label_google_sheet_id_asterik.setSizePolicy(sizePolicy)
        self.label_google_sheet_id_asterik.setStyleSheet("border:none;color:red;")
        self.label_google_sheet_id_asterik.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_google_sheet_id_asterik.setIndent(0)
        self.label_google_sheet_id_asterik.setObjectName("label_google_sheet_id_asterik")
        self.gridLayout_5.addWidget(self.label_google_sheet_id_asterik, 1, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_google_sheet_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setStyleSheet("border:none;color:red;")
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_16.setIndent(0)
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 1, 6, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_google_sheet_settings, 0, 2, 1, 2)
        self.tabWidget.addTab(self.tab_usingFile, "")
        self.gridLayout_6.addWidget(self.tabWidget, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(50)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("")
        self.label_7.setText("")
        self.label_7.setTextFormat(QtCore.Qt.RichText)
        self.label_7.setPixmap(QtGui.QPixmap("./resources/header6.gif"))
        # self.label_7.setPixmap(QtGui.QPixmap("C:\\Users\\Leverify\\Documents\\stock estimation code\\offers_stock_15K+\\resources\\header6.gif"))
        self.label_7.setScaledContents(True)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 2, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1641, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BI Department - Automation"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Excel File Settings"))
        self.label_select_excel_file_asterik.setText(_translate("MainWindow", "*"))
        self.label_2.setText(_translate("MainWindow", "Select File"))
        self.lineEdit_file_name.setPlaceholderText(_translate("MainWindow", "Choose file..."))
        self.pushButton_choice_file.setText(_translate("MainWindow", "..."))
        self.groupBox_3.setTitle(_translate("MainWindow", "Result Window"))
        self.pushButton_save.setToolTip(_translate("MainWindow", "Download Button"))
        self.pushButton_clear.setToolTip(_translate("MainWindow", "Clear Button"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Action"))
        self.label_overallExportStatus.setText(_translate("MainWindow", "Not Started Yet !!!"))
        self.label_5.setText(_translate("MainWindow", "Status"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Console"))
        self.textBrowser_console.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">WELCOME TO STOCK ESTIMATION..!!</span></p></body></html>"))
        self.pushButton_export.setToolTip(_translate("MainWindow", "Run Script"))
        self.groupBox_initial_settings.setTitle(_translate("MainWindow", "Initial Configuration"))
        self.label_15.setText(_translate("MainWindow", "*"))
        self.radioButton_source_excel_sheet.setText(_translate("MainWindow", "Excel File"))
        self.label.setText(_translate("MainWindow", "ASIN Source"))
        self.radioButton_source_google_sheet.setText(_translate("MainWindow", "Google sheet"))
        self.groupBox_google_sheet_settings.setTitle(_translate("MainWindow", "Google Sheet Settings"))
        self.label_4.setText(_translate("MainWindow", "Id"))
        self.lineEdit_googlesheet_id.setPlaceholderText(_translate("MainWindow", "Enter Google Sheet Id"))
        self.lineEdit_googlesheet_name.setPlaceholderText(_translate("MainWindow", "Enter Tab Name"))
        self.label_google_sheet_name_asterik.setText(_translate("MainWindow", "Name"))
        self.label_google_sheet_id_asterik.setText(_translate("MainWindow", "*"))
        self.label_16.setText(_translate("MainWindow", "*"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_usingFile), _translate("MainWindow", "Using File"))


        self.pushButton_choice_file.clicked.connect(
            lambda: self.dialog(self.pushButton_choice_file))

        self.pushButton_export.clicked.connect(lambda: self.run())

        self.pushButton_save.clicked.connect(lambda: self.save())

        self.pushButton_clear.clicked.connect(lambda: self.clear())

    def dialog(self, button_name):
        file, check = QFileDialog.getOpenFileName(None, "QFileDialog.getOpenFileName()",
                                                  "", "Excel Files (*.xlsx)")
        if check:
            sending_button = button_name.sender()
            btn_name = sending_button.objectName()

            if btn_name == "pushButton_choice_file":
                self.lineEdit_file_name.setText(file)

    def run(self):
        word1 = '<span style=\" color: #ffd15c;font-weight:bold 9px;\">%s</span>' % "Exporting in Process"
        word2 = '<span style=\" color: #ffd15c;font-weight:bold 9px;\">%s<br></span>' % "================="
        self.textBrowser_console.setText(word1)
        self.textBrowser_console.append(word2)
        if self.radioButton_source_excel_sheet.isChecked():
            if (len(self.lineEdit_googlesheet_id.text()) == 0) or (len(self.lineEdit_googlesheet_name.text()) == 0) or (len(self.lineEdit_file_name.text()) == 0) or ( (len(self.lineEdit_googlesheet_id.text()) == 0) and (len(self.lineEdit_googlesheet_name.text()) == 0) and (len(self.lineEdit_file_name.text()) == 0)):
                word6 = '<span style=\" color: #FC2701;font-weight:bold;\">%s</span>' % " PLEASE FULFIL ALL REQUIREMENTS"
                self.textBrowser_console.setText(word6)
                QtWidgets.QMessageBox.information(MainWindow, 'Message', 'Please Fulfil all Requirements !!!',
                                                  QtWidgets.QMessageBox.Ok)
            else:
                google_id = self.lineEdit_googlesheet_id.text()
                worksheet_name_to_store = self.lineEdit_googlesheet_name.text()
                excel_sheet_address = self.lineEdit_file_name.text()
                self.label_overallExportStatus.setText("PROCESS STARTED")
                
                # self.thread = MainFile("EXCEL", google_id, worksheet_name_to_store,excel_sheet_address)
                # self.thread.start()
                # self.thread.progressbar.connect(self.progressbar)
                # self.thread.update.connect(self.update)
                # self.thread.finished.connect(self.close)
                try:
                        self.thread = MainFile("EXCEL", google_id, worksheet_name_to_store,excel_sheet_address)
                        self.thread.start()
                        self.thread.progressbar.connect(self.progressbar)
                        self.thread.update.connect(self.update)
                        self.thread.finished.connect(self.close)
                except Exception as error:
                        print(error)
                        no_internet = '<span style=\" color: #D5462C;font-weight:bold;\">%s</span>' % "Error.... Try Again"
                        self.textBrowser_console.setText(error)


        elif self.radioButton_source_google_sheet.isChecked():
            if (len(self.lineEdit_googlesheet_id.text()) == 0) or (len(self.lineEdit_googlesheet_name.text()) == 0) or ( (len(self.lineEdit_googlesheet_id.text()) == 0) and (len(self.lineEdit_googlesheet_name.text()) == 0)):
                word6 = '<span style=\" color: #FC2701;font-weight:bold;\">%s</span>' % " PLEASE FULFIL ALL REQUIREMENTS"
                self.textBrowser_console.setText(word6)
                QtWidgets.QMessageBox.information(MainWindow, 'Message', 'Please Fulfil all Requirements !!!',
                                                  QtWidgets.QMessageBox.Ok)
            else:
                google_id = self.lineEdit_googlesheet_id.text()
                worksheet_name_to_store = self.lineEdit_googlesheet_name.text()
                excel_sheet_address = "NO ADDRESS REQUIRED"
                self.label_overallExportStatus.setText("PROCESS STARTED")
                # self.thread = MainFile("GOOGLE", google_id, worksheet_name_to_store, excel_sheet_address)
                # self.thread.start()
                # self.thread.progressbar.connect(self.progressbar)
                # self.thread.update.connect(self.update)
                # self.thread.finished.connect(self.close)
                try:
                        self.thread = MainFile("GOOGLE", google_id, worksheet_name_to_store, excel_sheet_address)
                        self.thread.start()
                        self.thread.progressbar.connect(self.progressbar)
                        self.thread.update.connect(self.update)
                        self.thread.finished.connect(self.close)
                except Exception as error:
                        print(error)
                        no_internet = '<span style=\" color: #D5462C;font-weight:bold;\">%s</span>' % "Error.... Try Again"
                        self.textBrowser_console.setText(error)
                
        else:
            word5 = '<span style=\" color: #D5462C;font-weight:bold;\">%s</span>' % "No Option is Selected !"
            self.textBrowser_console.setText(word5)
            QtWidgets.QMessageBox.information(MainWindow, 'Message', 'No Option is Selected !!!',
                                              QtWidgets.QMessageBox.Ok)

    def save(self):
        # google_id = self.lineEdit_googlesheet_id.text()
        # worksheet_name_to_store = self.lineEdit_googlesheet_name.text()
        # stock_sheet_object = GoogleSheet_SE("./resources/client_secret.json", google_id)
        # # stock_sheet_object = GoogleSheet_SE("C:\\Users\\Leverify\\Documents\\stock estimation code\\offers_stock_15K+\\resources\\client_secret.json", google_id)
        # self.stock_data_save = stock_sheet_object.datatostore(stock_sheet_object, worksheet_name_to_store)
        # date_today = datetime.datetime.now()
        # date = date_today.strftime("%d/%m/%Y")
        # stockdates = date.replace("/", "_")
        # stock_filename = "%s.csv" % stockdates
        # with open(stock_filename, 'w') as csvfile:
        #     csvwriter = csv.writer(csvfile)
        #     csvwriter.writerows(self.stock_data_save)

        self.textBrowser_console.append("SHEET DOWNLOADED SUCCESSFULLY")

    def clear(self):
        self.tableWidget_employees.clear()
        self.tableWidget_employees.setColumnCount(0)
        self.tableWidget_employees.setRowCount(0)
        self.textBrowser_console.append("Table Contents Cleared..")

    def update(self,update_str):
        self.textBrowser_console.append(update_str)

    def progressbar(self,num):
        self.progressBar_export.setProperty("value", num)

    def close(self):
        word1 = '<span style=\" color: #ffd15c;font-weight:bold 9px;\">%s</span>' % "Exporting Process Completed"
        word2 = '<span style=\" color: #ffd15c;font-weight:bold 9px;\">%s<br></span>' % "================="
        self.textBrowser_console.append(word1)
        self.textBrowser_console.append(word2)
        self.label_overallExportStatus.setText("Process Completed")
        self.tableWidget_employees.setColumnCount(15)
        google_id = self.lineEdit_googlesheet_id.text()
        worksheet_name_to_store = self.lineEdit_googlesheet_name.text()
        stock_sheet_object = GoogleSheet_SE("./resources/client_secret.json", google_id)
        # stock_sheet_object = GoogleSheet_SE("C:\\Users\\Leverify\\Documents\\stock estimation code\\offers_stock_15K+\\resources\\client_secret.json", google_id)
        self.stock_data_save = stock_sheet_object.datatostore(stock_sheet_object, worksheet_name_to_store)
        try:
                length = len(self.stock_data_save)
                length_col = len(self.stock_data_save[0])
                # length_col= 14
                self.tableWidget_employees.setRowCount(length - 1)
                self.tableWidget_employees.setStyleSheet("border:1px solid white;\n"
                                                        "background-color: rgb(255, 255, 255);\n"
                                                        "color:black;\n"
                                                        "font: bold")
                self.tableWidget_employees.setHorizontalHeaderLabels(self.stock_data_save[0])
                self.tableWidget_employees.setStyleSheet("border:1px solid white;\n"
                                                        "background-color: rgb(255, 255, 255);\n"
                                                        "color:black;")
                x = 0
                for i in range(0, length):
                        for j in range(0, length_col):
                                x = i + 1
                                if x == length:
                                        break
                                else:
                                        data = QTableWidgetItem(self.stock_data_save[x][j])
                                        self.tableWidget_employees.setItem(i, j, data)
                self.textBrowser_console.append("Data Displayed as well..")
        except Exception as error:
                self.textBrowser_console.append(".... E N D ....")
                
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
